#!/usr/bin/env bash
#
# scripts/import_apteki.sh
#
# Pobranie rzeczywistych aptek z OpenStreetMap (Overpass API) w obrębie
# bounding boxa Warszawy (52.10, 20.85, 52.37, 21.27) i ich import do
# tabeli `public.apteki` w bazie PostGIS uruchomionej w kontenerze Docker.
#
# Krok 1: pobranie JSON-a z Overpass do data/apteki.json
# Krok 2: TRUNCATE TABLE public.apteki RESTART IDENTITY CASCADE
# Krok 3: parsowanie JSON-a (Python stdlib) -> wygenerowanie SQL-a INSERT
# Krok 4: zaaplikowanie SQL-a wewnątrz kontenera (`docker compose exec -T db psql`)
#
# Konwersja współrzędnych: EPSG:4326 -> EPSG:2180 za pomocą
# ST_Transform(ST_SetSRID(ST_Point(lon, lat), 4326), 2180).
#
# Wymagania: bash, curl, python3 (stdlib), docker compose, działający kontener `db`.
# Kompatybilność: macOS Bash 3.2 + Linux.

set -euo pipefail

# -------------------------------------------------------------------- Ścieżki
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DATA_DIR="${REPO_ROOT}/data"
JSON_PATH="${DATA_DIR}/apteki.json"
SQL_PATH="${DATA_DIR}/apteki_insert.sql"

mkdir -p "${DATA_DIR}"

# ------------------------------------------------------------- Konfiguracja DB
DB_SERVICE="${DB_SERVICE:-db}"
DB_USER="${DB_USER:-postgres}"
DB_NAME="${DB_NAME:-warszawa_health}"

# ----------------------------------------------------- Endpointy Overpass API
# Główny + fallbacki (3 niezależne instancje).
OVERPASS_ENDPOINTS=(
    "https://overpass.kumi.systems/api/interpreter"
    "https://overpass.private.coffee/api/interpreter"
    "https://overpass-api.de/api/interpreter"
)

# Zapytanie Overpass — apteki w bbox Warszawy (S,W,N,E).
OVERPASS_QUERY='[out:json][timeout:90];
node["amenity"="pharmacy"](52.10,20.85,52.37,21.27);
out body;'

# ---------------------------------------------------------------------- 1. Fetch
echo "[1/4] Pobieranie aptek z Overpass API..."

fetched=0
for endpoint in "${OVERPASS_ENDPOINTS[@]}"; do
    echo "      -> ${endpoint}"
    if curl -sS --max-time 120 --fail \
            -X POST -d "data=${OVERPASS_QUERY}" \
            "${endpoint}" -o "${JSON_PATH}.tmp"; then
        # Sanity check: poprawny JSON + niepuste 'elements'
        if python3 -c "import json,sys; d=json.load(open('${JSON_PATH}.tmp')); sys.exit(0 if isinstance(d.get('elements'),list) and len(d['elements'])>0 else 1)"; then
            mv "${JSON_PATH}.tmp" "${JSON_PATH}"
            fetched=1
            break
        else
            echo "      (pusta odpowiedź, próbuję kolejny endpoint)"
            rm -f "${JSON_PATH}.tmp"
        fi
    else
        echo "      (błąd HTTP, próbuję kolejny endpoint)"
        rm -f "${JSON_PATH}.tmp"
    fi
done

if [ "${fetched}" -ne 1 ]; then
    echo "BŁĄD: nie udało się pobrać danych z żadnego endpointu Overpass." >&2
    exit 1
fi

echo "      Plik zapisany: ${JSON_PATH}"

# --------------------------------------------------- 2. Wygenerowanie SQL-a
echo "[2/4] Generowanie SQL-a INSERT z JSON-a..."

python3 - <<PYEOF > "${SQL_PATH}"
import json, sys

with open("${JSON_PATH}", "r", encoding="utf-8") as fh:
    data = json.load(fh)

elements = data.get("elements", [])

def sql_str(value):
    if value is None:
        return "NULL"
    safe = str(value).replace("'", "''")
    return "'" + safe + "'"

print("-- Auto-generated by scripts/import_apteki.sh")
print("BEGIN;")
print("TRUNCATE TABLE public.apteki RESTART IDENTITY CASCADE;")
print()

inserted = 0
for el in elements:
    if el.get("type") != "node":
        continue
    lon = el.get("lon"); lat = el.get("lat")
    if lon is None or lat is None:
        continue
    tags = el.get("tags", {}) or {}
    name = tags.get("name") or tags.get("brand") or "Apteka"
    street = tags.get("addr:street", "")
    number = tags.get("addr:housenumber", "")
    addr = (street + (" " + number if number else "")).strip()
    addr_sql = sql_str(addr) if addr else "NULL"
    print(
        "INSERT INTO public.apteki (nazwa, adres, geom) VALUES ("
        + sql_str(name) + ", "
        + addr_sql + ", "
        + "ST_Transform(ST_SetSRID(ST_Point("
        + f"{lon:.7f}, {lat:.7f}" + "), 4326), 2180));"
    )
    inserted += 1

print()
print("COMMIT;")
print(f"-- Wstawiono rekordów: {inserted}")
print(f"\\echo Zaimportowano {inserted} aptek z OpenStreetMap")
PYEOF

count=$(grep -c "^INSERT INTO public.apteki" "${SQL_PATH}" || echo 0)
echo "      Wygenerowano ${count} insertów (${SQL_PATH})"

# ------------------------------------------- 3+4. Aplikacja SQL-a w kontenerze
echo "[3/4] Sprawdzenie kontenera bazy..."
if ! docker compose ps --services --filter status=running | grep -qx "${DB_SERVICE}"; then
    echo "BŁĄD: kontener '${DB_SERVICE}' nie działa. Uruchom: docker compose up -d" >&2
    exit 1
fi

echo "[4/4] Aplikacja SQL-a w kontenerze..."
docker compose exec -T "${DB_SERVICE}" \
    psql -U "${DB_USER}" -d "${DB_NAME}" \
        -v ON_ERROR_STOP=1 < "${SQL_PATH}"

echo
echo "Import zakończony pomyślnie."
docker compose exec -T "${DB_SERVICE}" \
    psql -U "${DB_USER}" -d "${DB_NAME}" -At \
        -c "SELECT 'apteki_w_bazie='||COUNT(*) FROM public.apteki;"
